"""ordens compartilhadas"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ordem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("produto", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("especificacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("quantidade", sa.Integer(), nullable=False),
        sa.Column("unidade", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prioridade", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prazo", sa.DateTime(), nullable=False),
        sa.Column("observacao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("solicitante_id", sa.Integer(), nullable=False),
        sa.Column("responsavel_id", sa.Integer(), nullable=True),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("pronto_em", sa.DateTime(), nullable=True),
        sa.Column("coletado_em", sa.DateTime(), nullable=True),
        sa.Column("coletado_por", sa.Integer(), nullable=True),
        sa.Column("cancelado_em", sa.DateTime(), nullable=True),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["coletado_por"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsavel_id"],
            ["usuario.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_ordem_status"), "ordem", ["status"], unique=False)
    op.create_table(
        "eventoordem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ordem_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("usuario_nome", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("acao", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status_anterior", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status_novo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("motivo", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("versao", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ordem_id"],
            ["ordem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ordem_id", "versao"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(op.f("ix_eventoordem_ordem_id"), "eventoordem", ["ordem_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "Ordens possuem histórico operacional. Restaure backup validado para reverter."
    )
