"""avisos de produtos"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notificacao",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evento_id", sa.Integer(), nullable=False),
        sa.Column("ordem_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("mensagem", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("lida_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evento_id"],
            ["eventoordem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ordem_id"],
            ["ordem.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuario.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evento_id", "usuario_id"),
    )
    op.create_index(
        "ix_notificacao_usuario_lida", "notificacao", ["usuario_id", "lida_em"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError(
        "Avisos possuem histórico de leitura. Restaure backup validado para reverter."
    )
